@echo off
setlocal
cd /d "%~dp0"
set OUT=%CD%\event_dump.txt

powershell -NoProfile -ExecutionPolicy Bypass -Command "$out='event_dump.txt'; $sep=('='*70); $sep | Out-File $out -Encoding utf8; 'SECTION 1: SFCleaner / .NET / AppModel errors (Application log, last 72h)' | Out-File $out -Append -Encoding utf8; $sep | Out-File $out -Append -Encoding utf8; Get-WinEvent -FilterHashtable @{LogName='Application'; Level=1,2,3; StartTime=(Get-Date).AddHours(-72)} -ErrorAction SilentlyContinue | Where-Object { $_.Message -match 'SFCleaner|\.NET Runtime|Application Error|AppModel|Windows App SDK|MddBootstrap|Xaml' -or $_.ProviderName -match 'NET Runtime|Application Error|Windows Error Reporting|AppModel' } | Select-Object -First 40 | ForEach-Object { ('[{0}] {1} (EventID {2})' -f $_.TimeCreated, $_.ProviderName, $_.Id); $_.Message; ('-'*70) } | Out-File $out -Append -Encoding utf8; 'SECTION 2: BSOD history (System log, BugCheck/Kernel-Power, last 7 days)' | Out-File $out -Append -Encoding utf8; $sep | Out-File $out -Append -Encoding utf8; Get-WinEvent -FilterHashtable @{LogName='System'; ProviderName='Microsoft-Windows-WER-SystemErrorReporting','Microsoft-Windows-Kernel-Power','BugCheck'; StartTime=(Get-Date).AddDays(-7)} -ErrorAction SilentlyContinue | Select-Object -First 20 | ForEach-Object { ('[{0}] {1} (EventID {2})' -f $_.TimeCreated, $_.ProviderName, $_.Id); $_.Message; ('-'*70) } | Out-File $out -Append -Encoding utf8; 'SECTION 3: last 15 Application-log errors regardless of source' | Out-File $out -Append -Encoding utf8; $sep | Out-File $out -Append -Encoding utf8; Get-WinEvent -FilterHashtable @{LogName='Application'; Level=2; StartTime=(Get-Date).AddHours(-72)} -ErrorAction SilentlyContinue | Select-Object -First 15 | ForEach-Object { ('[{0}] {1} (EventID {2})' -f $_.TimeCreated, $_.ProviderName, $_.Id); $_.Message; ('-'*70) } | Out-File $out -Append -Encoding utf8; Write-Host ''; Write-Host ('DONE -> ' + (Resolve-Path $out).Path)"

echo.
notepad event_dump.txt
